services:
  - type: web
    name: lavexpress-api
    env: docker
    dockerfilePath: ./laveexpress-backend/Dockerfile
    dockerContext: ./laveexpress-backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        value: LavExpressTCC2024JwtSecretKeyAutenticacaoSistemaAgendamentoLavajatoSeguroComMaisDe64Caracteres
      - key: DATABASE_URL
        fromDatabase:
          name: lavexpress-db
          property: connectionString
    healthCheckPath: /actuator/health

databases:
  - name: lavexpress-db
    databaseName: lavexpressdb
    user: lavexpressdb_user
    plan: free