spring.datasource.url=jdbc:postgresql://localhost:5432/lavexpress_db
spring.datasource.username=postgres
spring.datasource.password=Cabideverde10
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=1000

jwt.secret=LavExpressTCC2024JwtSecretKeyAutenticacaoSistemaAgendamentoLavajatoSeguroComMaisDe64Caracteres
jwt.expiration=864000000