server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 864000000

logging:
  level:
    com.lavexpress: INFO
    org.springframework.security: WARN
    org.hibernate: WARN